export enum AVPlayPlayerState {
	NONE = 'NONE',
	IDLE = 'IDLE',
	READY = 'READY',
	PLAYING = 'PLAYING',
	PAUSED = 'PAUSED'
}

export enum AVPlaySpeed {
	X32 = 32,
	X16 = 16,
	X8 = 8,
	X4 = 4,
	X2 = 2,
	X1 = 1,
	REW1 = -1,
	REW2 = -2,
	REW4 = -4,
	REW8 = -8,
	REW16 = -16,
	REW32 = -32
}

export enum AVPlayDisplayMethod {
	PLAYER_DISPLAY_MODE_LETTER_BOX = 'PLAYER_DISPLAY_MODE_LETTER_BOX',
	PLAYER_DISPLAY_MODE_ORIGIN_SIZE = 'PLAYER_DISPLAY_MODE_ORIGIN_SIZE',
	PLAYER_DISPLAY_MODE_FULL_SCREEN = 'PLAYER_DISPLAY_MODE_FULL_SCREEN',
	PLAYER_DISPLAY_MODE_CROPPED_FULL = 'PLAYER_DISPLAY_MODE_CROPPED_FULL',
	PLAYER_DISPLAY_MODE_ZOOM_HALF = 'PLAYER_DISPLAY_MODE_ZOOM_HALF',
	PLAYER_DISPLAY_MODE_ZOOM_THREE_QUARTERS = 'PLAYER_DISPLAY_MODE_ZOOM_THREE_QUARTERS',
	PLAYER_DISPLAY_MODE_ORIGIN_OR_LETTER = 'PLAYER_DISPLAY_MODE_ORIGIN_OR_LETTER',
	PLAYER_DISPLAY_MODE_DST_ROI = 'PLAYER_DISPLAY_MODE_DST_ROI',
	PLAYER_DISPLAY_MODE_ZOOM_16_9 = 'PLAYER_DISPLAY_MODE_ZOOM_16_9',
	PLAYER_DISPLAY_MODE_ZOOM = 'PLAYER_DISPLAY_MODE_ZOOM',
	PLAYER_DISPLAY_MODE_ZOOM_CUSTOM = 'PLAYER_DISPLAY_MODE_ZOOM_CUSTOM',
	PLAYER_DISPLAY_MODE_AUTO_ASPECT_RATIO = 'PLAYER_DISPLAY_MODE_AUTO_ASPECT_RATIO'
}

export enum AVPlayStreamingPropertyType {
	COOKIE = 'COOKIE',
	USER_AGENT = 'USER_AGENT',
	PREBUFFER_MODE = 'PREBUFFER_MODE',
	ADAPTIVE_INFO = 'ADAPTIVE_INFO',
	SET_MODE_3D = 'SET_MODE_3D',
	SET_MODE_4K = 'SET_MODE_4K',
	HD_AUDIO = 'HD_AUDIO',
	WIDEVINE = 'WIDEVINE'
}

export enum AVPlayDrmType {
	PLAY_READY = 'PLAYREADY',
	MARLIN = 'MARLIN',
	VERIMATRIX = 'VERIMATRIX',
	WIDEVINE_CLASSIC = 'WIDEVINE_CLASSIC',
	SECUREMEDIA = 'SECUREMEDIA',
	SDRM = 'SDRM'
}

export enum AVPlayDrmOperation {
	SET_PROPERTIES = 'SETPROPERTIES',
	GEN_CHALLENGE = 'GENCHALLENGE',
	INSTALL_LICENSE = 'INSTALLLICENSE',
	DELETE_LICENSE = 'DELETELICENSE',
	PROCESS_INITIATOR = 'PROCESSINITIATOR',
	GET_VERSION = 'GETVERSION'
}

export enum AVPlayStreamType {
	VIDEO = 'VIDEO',
	AUDIO = 'AUDIO',
	TEXT = 'TEXT'
}

export enum WebAPIExceptionCode {
	INDEX_SIZE_ERR = 1,
	DOMSTRING_SIZE_ERR = 2,
	HIERARCHY_REQUEST_ERR = 3,
	WRONG_DOCUMENT_ERR = 4,
	INVALID_CHARACTER_ERR = 5,
	NO_DATA_ALLOWED_ERR = 6,
	NO_MODIFICATION_ALLOWED_ERR = 7,
	NOT_FOUND_ERR = 8,
	NOT_SUPPORTED_ERR = 9,
	INUSE_ATTRIBUTE_ERR = 10,
	INVALID_STATE_ERR = 11,
	SYNTAX_ERR = 12,
	INVALID_MODIFICATION_ERR = 13,
	NAMESPACE_ERR = 14,
	INVALID_ACCESS_ERR = 15,
	VALIDATION_ERR = 16,
	TYPE_MISMATCH_ERR = 17,
	SECURITY_ERR = 18,
	NETWORK_ERR = 19,
	ABORT_ERR = 20,
	URL_MISMATCH_ERR = 21,
	QUOTA_EXCEEDED_ERR = 22,
	TIMEOUT_ERR = 23,
	INVALID_NODE_TYPE_ERR = 24,
	DATA_CLONE_ERR = 25
}
